/* This file is automatically generated from the migration tool utils package */
import type { MigrationStep } from "@com.mgmtp.a12.migrationtool/migrationtool-core/types";
import Schema_36_0_0 from "./version-36.0.0/schema.json" with { type: "json" };

import Schema_36_4_0_alpha_1 from "./version-36.4.0-alpha.1/schema.json" with { type: "json" };
import Schema_36_4_0 from "./version-36.4.0/schema.json" with { type: "json" };

import Schema_37_0_0_pre_1 from "./version-37.0.0-pre.1/schema.json" with { type: "json" };
import Schema_37_0_0_pre_2 from "./version-37.0.0-pre.2/schema.json" with { type: "json" };
import Schema_37_0_0 from "./version-37.0.0/schema.json" with { type: "json" };

import Schema_38_0_0_pre_1 from "./version-38.0.0-pre.1/schema.json" with { type: "json" };
import Schema_38_0_0_pre_2 from "./version-38.0.0-pre.2/schema.json" with { type: "json" };
import Transform_38_0_0_pre_2 from "./version-38.0.0-pre.2/transform.js";
import Schema_38_0_0 from "./version-38.0.0/schema.json" with { type: "json" };

import Schema_38_1_0_pre_1 from "./version-38.1.0-pre.1/schema.json" with { type: "json" };
import Schema_38_1_0_pre_2 from "./version-38.1.0-pre.2/schema.json" with { type: "json" };
import Schema_38_1_0_pre_3 from "./version-38.1.0-pre.3/schema.json" with { type: "json" };
import Schema_38_1_0 from "./version-38.1.0/schema.json" with { type: "json" };

import Schema_38_2_0_pre_1 from "./version-38.2.0-pre.1/schema.json" with { type: "json" };
import Schema_38_2_0 from "./version-38.2.0/schema.json" with { type: "json" };

import Schema_38_3_0_pre_1 from "./version-38.3.0-pre.1/schema.json" with { type: "json" };
import Schema_38_3_0 from "./version-38.3.0/schema.json" with { type: "json" };

export const MIGRATION_STEPS: MigrationStep[] = [
	{ version: "36.0.0", schema: Schema_36_0_0 },

	{ version: "36.4.0-alpha.1", schema: Schema_36_4_0_alpha_1 },
	{ version: "36.4.0", schema: Schema_36_4_0 },

	{ version: "37.0.0-pre.1", schema: Schema_37_0_0_pre_1 },
	{ version: "37.0.0-pre.2", schema: Schema_37_0_0_pre_2 },
	{ version: "37.0.0", schema: Schema_37_0_0 },

	{ version: "38.0.0-pre.1", schema: Schema_38_0_0_pre_1 },
	{ version: "38.0.0-pre.2", schema: Schema_38_0_0_pre_2, transform: Transform_38_0_0_pre_2 },
	{ version: "38.0.0", schema: Schema_38_0_0 },

	{ version: "38.1.0-pre.1", schema: Schema_38_1_0_pre_1 },
	{ version: "38.1.0-pre.2", schema: Schema_38_1_0_pre_2 },
	{ version: "38.1.0-pre.3", schema: Schema_38_1_0_pre_3 },
	{ version: "38.1.0", schema: Schema_38_1_0 },

	{ version: "38.2.0-pre.1", schema: Schema_38_2_0_pre_1 },
	{ version: "38.2.0", schema: Schema_38_2_0 },

	{ version: "38.3.0-pre.1", schema: Schema_38_3_0_pre_1 },
	{ version: "38.3.0", schema: Schema_38_3_0 }
];
