/* This file is automatically generated from the migration tool utils package */
import type { MigrationStep } from "@com.mgmtp.a12.migrationtool/migrationtool-core/types";
import Schema_37_0_0 from "./version-37.0.0/schema.json" with { type: "json" };

import Schema_38_0_0_pre_1 from "./version-38.0.0-pre.1/schema.json" with { type: "json" };
import Schema_38_0_0_pre_2 from "./version-38.0.0-pre.2/schema.json" with { type: "json" };
import Transform_38_0_0_pre_2 from "./version-38.0.0-pre.2/transform.js";
import Schema_38_0_0 from "./version-38.0.0/schema.json" with { type: "json" };

import Schema_38_1_0_pre_1 from "./version-38.1.0-pre.1/schema.json" with { type: "json" };
import Schema_38_1_0_pre_2 from "./version-38.1.0-pre.2/schema.json" with { type: "json" };
import Schema_38_1_0_pre_3 from "./version-38.1.0-pre.3/schema.json" with { type: "json" };
import Schema_38_1_0 from "./version-38.1.0/schema.json" with { type: "json" };

import Schema_38_2_0_pre_1 from "./version-38.2.0-pre.1/schema.json" with { type: "json" };
import Schema_38_2_0 from "./version-38.2.0/schema.json" with { type: "json" };

import Schema_38_3_0_pre_1 from "./version-38.3.0-pre.1/schema.json" with { type: "json" };
import Schema_38_3_0 from "./version-38.3.0/schema.json" with { type: "json" };

import Schema_39_0_0_pre_1 from "./version-39.0.0-pre.1/schema.json" with { type: "json" };
import Schema_39_0_0_pre_2 from "./version-39.0.0-pre.2/schema.json" with { type: "json" };
import Transform_39_0_0_pre_2 from "./version-39.0.0-pre.2/transform.js";
import Schema_39_0_0_pre_3 from "./version-39.0.0-pre.3/schema.json" with { type: "json" };
import Schema_39_0_0_pre_4 from "./version-39.0.0-pre.4/schema.json" with { type: "json" };
import Schema_39_0_0_pre_5 from "./version-39.0.0-pre.5/schema.json" with { type: "json" };
import Transform_39_0_0_pre_5 from "./version-39.0.0-pre.5/transform.js";
import Schema_39_0_0_pre_6 from "./version-39.0.0-pre.6/schema.json" with { type: "json" };
import Transform_39_0_0_pre_6 from "./version-39.0.0-pre.6/transform.js";
import Schema_39_0_0_pre_7 from "./version-39.0.0-pre.7/schema.json" with { type: "json" };
import Transform_39_0_0_pre_7 from "./version-39.0.0-pre.7/transform.js";
import Schema_39_0_0_pre_8 from "./version-39.0.0-pre.8/schema.json" with { type: "json" };
import Transform_39_0_0_pre_8 from "./version-39.0.0-pre.8/transform.js";
import Schema_39_0_0_pre_9 from "./version-39.0.0-pre.9/schema.json" with { type: "json" };
import Schema_39_0_0 from "./version-39.0.0/schema.json" with { type: "json" };

export const MIGRATION_STEPS: MigrationStep[] = [
	{ version: "37.0.0", schema: Schema_37_0_0 },

	{ version: "38.0.0-pre.1", schema: Schema_38_0_0_pre_1 },
	{ version: "38.0.0-pre.2", schema: Schema_38_0_0_pre_2, transform: Transform_38_0_0_pre_2 },
	{ version: "38.0.0", schema: Schema_38_0_0 },

	{ version: "38.1.0-pre.1", schema: Schema_38_1_0_pre_1 },
	{ version: "38.1.0-pre.2", schema: Schema_38_1_0_pre_2 },
	{ version: "38.1.0-pre.3", schema: Schema_38_1_0_pre_3 },
	{ version: "38.1.0", schema: Schema_38_1_0 },

	{ version: "38.2.0-pre.1", schema: Schema_38_2_0_pre_1 },
	{ version: "38.2.0", schema: Schema_38_2_0 },

	{ version: "38.3.0-pre.1", schema: Schema_38_3_0_pre_1 },
	{ version: "38.3.0", schema: Schema_38_3_0 },

	{ version: "39.0.0-pre.1", schema: Schema_39_0_0_pre_1 },
	{ version: "39.0.0-pre.2", schema: Schema_39_0_0_pre_2, transform: Transform_39_0_0_pre_2 },
	{ version: "39.0.0-pre.3", schema: Schema_39_0_0_pre_3 },
	{ version: "39.0.0-pre.4", schema: Schema_39_0_0_pre_4 },
	{ version: "39.0.0-pre.5", schema: Schema_39_0_0_pre_5, transform: Transform_39_0_0_pre_5 },
	{ version: "39.0.0-pre.6", schema: Schema_39_0_0_pre_6, transform: Transform_39_0_0_pre_6 },
	{ version: "39.0.0-pre.7", schema: Schema_39_0_0_pre_7, transform: Transform_39_0_0_pre_7 },
	{ version: "39.0.0-pre.8", schema: Schema_39_0_0_pre_8, transform: Transform_39_0_0_pre_8 },
	{ version: "39.0.0-pre.9", schema: Schema_39_0_0_pre_9 },
	{ version: "39.0.0", schema: Schema_39_0_0 }
];
