////
SPDX-License-Identifier: EUPL-1.2 OR LicenseRef-commercial
Copyright (c) 2012-2026 mgm technology partners GmbH
Dual License
This source file is part of the mgm A12 Platform and available under a choice of two different licenses:
1. Open-Source License - EUPL v1.2
You may redistribute and/or modify this file under the terms of the European Union Public License, version 1.2 - see https://eupl.eu/.
2. Commercial License
Alternatively, you may obtain a commercial license from mgm technology partners GmbH, that permits use of this software under different terms (including support and maintenance services).

Please contact a12-license@mgm-tp.com for more information.

You must select and comply with exactly one of the above license options.

Warranty Disclaimer (applies to either option)
THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTY OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT, EXCEPT WHERE SUCH DISCLAIMERS ARE HELD TO BE LEGALLY INVALID. SEE THE RESPECTIVE LICENSE TEXT FOR DETAILS. 
////
= Overview Engine component

`OverviewEngine` is the main React component that is used to render an Overview Engine. The props of `OverviewEngine` can belong to one of the following interfaces:

- `OverviewEngine.PaginatedProps`: is used to define paginated Overview Engines. See further details link:./assets/generated/typedoc/interfaces/view_overview-engine.OverviewEngine.PaginatedProps.html[here].
- `OverviewEngine.InfiniteScrollProps`: is used when infinite-scrolling is enabled. See further details link:./assets/generated/typedoc/interfaces/view_overview-engine.OverviewEngine.InfiniteScrollProps.html[here].

The following snippet presents the above interfaces in details, specifying properties with their corresponding functions:

[source,typescript,title="OverviewEngine Props"]
----
include::./assets/generated/typescript/overview-engine.ts[]
----

Mostly the component customization will be done at the Client level via view providers by extending/wrapping
link:./assets/generated/typedoc/variables/client-extensions_internal_factories.OverviewEngineFactories.ViewComponent.html[OverviewEngineFactories.ViewComponent] component.
In that case, it needs to ensure that the `handleProgressIndicator` flag is handled properly. Consider the following example:

[source,typescript,options="nowrap",title="Re-setting handleProgressIndicator for custom views"]
----
include::./assets/typescript/features/custom-overview-engine-view.tsx[tags=main]
----

Here the custom component re-uses the `OverviewEngineFactories.ViewComponent` component, which already sets `handleProgressIndicator` to true internally.
Therefore, it needs to also be set on the wrapped (custom) component when the default behavior should be kept.
