////
SPDX-License-Identifier: EUPL-1.2 OR LicenseRef-commercial
Copyright (c) 2012-2026 mgm technology partners GmbH
Dual License
This source file is part of the mgm A12 Platform and available under a choice of two different licenses:
1. Open-Source License - EUPL v1.2
You may redistribute and/or modify this file under the terms of the European Union Public License, version 1.2 - see https://eupl.eu/.
2. Commercial License
Alternatively, you may obtain a commercial license from mgm technology partners GmbH, that permits use of this software under different terms (including support and maintenance services).

Please contact a12-license@mgm-tp.com for more information.
    
You must select and comply with exactly one of the above license options.

Warranty Disclaimer (applies to either option)
THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTY OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT, EXCEPT WHERE SUCH DISCLAIMERS ARE HELD TO BE LEGALLY INVALID. SEE THE RESPECTIVE LICENSE TEXT FOR DETAILS. 
////
[#actions]
= Overview Engine Actions

The engine _actions_ are divided into two types: *_events_* and *_commands_*.

*Events* signal that something has happened in the UI, triggered by a user interaction. For example click a button on a row.
They are handled by middlewares and will never change the state directly.
They can be dispatched by users, for example `Events.onFilterChanged` to apply specific filters to the *Overview Engine*.
Developers are also encouraged to listen to them, for example to `Events.onEventButtonClicked` to get notified about an event button being clicked.

*Commands* are used to directly modify the Redux state. They are dispatched by other _Events/Commands_ and are usually implemented in reducers.
Users are encouraged to dispatch them, for example `Commands.setDisabled` to disable the UI, but are *NOT* encouraged to listen to them.
Which commands are dispatched in what order and by what user interaction is considered an implementation detail
and a change is not considered breaking.

*Why are actions separated into events and commands?*

This helps to understand the engine's runtime behavior better, because you can rely on the effect of actions
only creating other actions or changing the state. This makes maintenance, customizing, and debugging easier.

It also serves as a reminder not to listen to commands when you want to react to user interactions.
Which event is dispatched by what user interaction is fixed. Which commands are dispatched as a result might change and should not be relied on.

== Commands and Events

[#event-actions]
=== Events

All UI-Events trigger the dispatching of a Redux action. The behavior, which gets triggered by these events, can be changed by registering custom middlewares.
The following table describes what each action does and what user interaction leads to the action.

For a more details: action's payloads, please refer to the link:./assets/generated/typedoc/modules/store_internal_actions.Events.html[API documentation].

|===
|*Event*|Description|Dispatched by

|onSearched|trigger a full text search| the full text search input
|onInfiniteScrolled|update infinite scroll state| the scroll event of the table
|onPageClicked|change the current page to a specific one| the pagination block to select a specific page
|onNextPageClicked|change the current page to the next one| the pagination block to select the next page
|onPreviousPageClicked|change the current page to the previous one| the pagination block to select the previous page
|onFilterChanged|apply the filters| the apply button of the filter selector
|onSorted|change the sorting column| click event on a column header
|onMultiSelectionButtonClicked| toggle the multi-selection state| a click event on the collapse/expand multi-selection section
|onOverallMultiSelectionButtonClicked| select all rows of the current page for multi-selection| a click event on checkbox in the multi-selection column header
|onMultiSelectionCleared| deselect all multi-selected rows| after successfully apply a new filter or search
|onRowsSelected| select row(s) for multi-selection | a click event on multi-selection checkbox of a row
|onScrollToRow| programmatically scroll to a row | application code dispatching the event
|onEventButtonClicked| no usage, lets users react to button clicks| a click event on a subheader/footer's event button
|onEventButtonClickedRequest| request a confirmation dialog if configured by the button| a click event on a subheader/footer's event button
|onRowButtonClicked| no usage, lets users react to button clicks| a click event on a row's event button
|onRowButtonClickedRequest| request a confirmation dialog if configured by the button| a click event on a row's event button
|onRowClicked| no usage, lets users react to button clicks| a click event on a row
|onColumnWidthsChanged| resize the columns width| a resize event on resize handler between column's headers
|onDialogClosed| close the dialog| a close button of the dialog
|onDialogConfirmed| confirm the dialog| a confirm button of the dialog

|===

[#command-actions]
=== Commands

All direct state changes are coming from these actions. However, it is not recommended to listen to these actions directly.
What *Commands* are dispatched at what time and in what order is considered an implementation detail and may change any time in a *_non-breaking way_*.

It is possible to register custom reducers to take care about how information is stored.
But be aware that the engine components always need the store in a special structure to be able to render!

The following table shows an overview of all *Commands*.

For a detailed description, including the specific payloads, please refer to the link:./assets/generated/typedoc/modules/store_internal_actions.Commands.html[API documentation].


|===
|*Commands*|Description|State Change

|setDisabled|set disabled state for the engine| "disabled" in "uiState"
|setDialog|set the dialog information| "dialog" in "uiState"
|setColumnWidths|set the width of each table's column| "columnWidths" in "uiState"
|setRowState|set the row state| "rowState" in "uiState"
|setExpandedMultiSelection|set expansion state of multi-selection panel| "expandedMultiSelection" in "uiState"
|setQueryParameters|set query parameters| "searchString", "pagination", "scrolling", "sorting", "activeFilters" in "uiState"

|===

[#client-actions]
== Client Actions

The commands and events are specific to the engine and are not aware of the context where it belongs to.
This can be a problem when multiple instances of an engine are required, resulting in conflict between instances.
Therefore, the `OverviewEngineActions` namespace exists to allow adding context to the core's events and commands, e.g. `activityId` and other Client's related information.

The following table shows an overview of every action. For a detailed description, including the specific payloads, please refer to the
link:./assets/generated/typedoc/modules/client-extensions_internal_actions.OverviewEngineActions.html[API documentation].

|===
|*Actions*|Description

|OverviewEngineActions.createActivity|Action to create an Overview Engine activity with option to include initial UI state
|OverviewEngineActions.event|A wrapper action for *Events* while also includes the `activityId`
|OverviewEngineActions.command|A wrapper action for *Commands* while also includes the `activityId`
|OverviewEngineActions.createEnumeratedStringDataHolder| Create a data holder for an enumerated string filter option view
|OverviewEngineActions.enumeratedStringQueryParametersChanged| Trigger when the search input changed of the enumerated string filter option view
|OverviewEngineActions.setEnumeratedStringCandidates| Trigger after receiving the data for enumerated string filter option view
|===

[#dispatch-engine-action]
== Dispatch an Engine Action

In a usual A12 application, the engine runtime will NOT be able to react if only a bare <<#event-actions, event>> or <<#command-actions, command>> action
is dispatched. Those events or commands, which can be seen on Redux Devtool, are usually nested in a <<#client-actions, client action>>.
This internally allows some engine's core features set to be seperated from being dependent on the activity.

Therefore, to control the engine's runtime behaviors, it is necessary to be aware of this extra layer before dispatching an action.

[source,typescript,options="nowrap",title="dispatching-actions.ts"]
--
import { Events, Commands } from "@com.mgmtp.a12.overviewengine/overviewengine-core/lib/main/store";

import { OverviewEngineActions } from "@com.mgmtp.a12.overviewengine/overviewengine-core/lib/main/client-extensions";

// Middleware
const customMiddleware: Middleware = (api) => (next) => (action) => {
	// ...other logics
	api.dispatch(OverviewEngineActions.event({
        activityId: "MY_ACTIVITY_ID",
        engineAction: Events.onFilterChanged({ activeFilters: [] })
	}))
}

// Saga
function* customSagaHandler(): SagaGenerator<void> {
	// ...other logics
	yield put(OverviewEngineActions.command({
        activityId: "MY_ACTIVITY_ID",
        engineAction: Commands.setDisabled({ disabled: true })
	}))
}
--

[#listen-to-engine-action]
== Listen to an Engine Action

Similarly, to handle an event dispatched by the engine, it is necessary to assert the <<#client-actions, client action>>
before checking the <<#event-actions, event>>, as follows:

[source,typescript,options="nowrap",title="handle-custom-row-action-saga.ts"]
--
include::./assets/generated/typescript/handle-custom-event-saga.ts[tags="handleCustomRowActionSaga"]
--
