//// 
SPDX-License-Identifier: EUPL-1.2 OR LicenseRef-commercial
Copyright (c) 2012-2026 mgm technology partners GmbH
Dual License
This source file is part of the mgm A12 Platform and available under a choice of two different licenses:
1. Open-Source License - EUPL v1.2
You may redistribute and/or modify this file under the terms of the European Union Public License, version 1.2 - see https://eupl.eu/.
2. Commercial License
Alternatively, you may obtain a commercial license from mgm technology partners GmbH, that permits use of this software under different terms (including support and maintenance services).

Please contact a12-license@mgm-tp.com for more information.
    
You must select and comply with exactly one of the above license options.

Warranty Disclaimer (applies to either option)
THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTY OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT, EXCEPT WHERE SUCH DISCLAIMERS ARE HELD TO BE LEGALLY INVALID. SEE THE RESPECTIVE LICENSE TEXT FOR DETAILS. 
////
= Button

Buttons, defined in an Overview Model, are displayed in the header, footer or multi-selection panel of the Overview Engine.
However, adding buttons in the Overview Model only renders them on the UI without registering any handler for on-click events.

Overview Engine supports registering the handlers by passing a callback into link:./assets/generated/typedoc/interfaces/view_api.OverviewEngineApi.EventHandlers.html#onrowbuttonclick-1[onEventButtonClick] of `eventHandlers` prop.
When triggered, the callback receives two parameters:

- `event` -- event name of the button being clicked.
- `button` -- configuration of the clicked link:./assets/generated/typedoc/interfaces/overview-model.OverviewModel.Button.html[Button].

NOTE: `onEventButtonClick` is used to register handlers for any buttons no matter if they are on header, footer or multi-selection panel
