//// 
SPDX-License-Identifier: EUPL-1.2 OR LicenseRef-commercial
Copyright (c) 2012-2026 mgm technology partners GmbH
Dual License
This source file is part of the mgm A12 Platform and available under a choice of two different licenses:
1. Open-Source License - EUPL v1.2
You may redistribute and/or modify this file under the terms of the European Union Public License, version 1.2 - see https://eupl.eu/.
2. Commercial License
Alternatively, you may obtain a commercial license from mgm technology partners GmbH, that permits use of this software under different terms (including support and maintenance services).

Please contact a12-license@mgm-tp.com for more information.
    
You must select and comply with exactly one of the above license options.

Warranty Disclaimer (applies to either option)
THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTY OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT, EXCEPT WHERE SUCH DISCLAIMERS ARE HELD TO BE LEGALLY INVALID. SEE THE RESPECTIVE LICENSE TEXT FOR DETAILS. 
////
= Searching

The API for searching in Overview Engine gives you full control over the functionality.
To implement search:

* link:./assets/generated/typedoc/interfaces/store_internal_store.UiState.html#searchstring[uiState.searchString] is used to specify the current search value.
* link:./assets/generated/typedoc/interfaces/view_api.OverviewEngineApi.EventHandlers.html#onsearch[eventHandlers.onSearch] callback inside the
`eventHandlers` prop is triggered when focusing is on search input and Enter key is pressed or search button is clicked.
It can also be done via the `OverviewEngineActions.event`, more details in the <<_commands_and_events,Commands and Events>> section.

[NOTE]
Overview Engine performs a plain text string-based full text search using the Simple Search operator from Data Services.
For further information, refer to the link:/docs/DATA_SERVICES/dataservices-documentation-src/index.html#simple-search-operator[Data Services documentation].
