////
SPDX-License-Identifier: EUPL-1.2 OR LicenseRef-commercial
Copyright (c) 2012-2026 mgm technology partners GmbH
Dual License
This source file is part of the mgm A12 Platform and available under a choice of two different licenses:
1. Open-Source License - EUPL v1.2
You may redistribute and/or modify this file under the terms of the European Union Public License, version 1.2 - see https://eupl.eu/.
2. Commercial License
Alternatively, you may obtain a commercial license from mgm technology partners GmbH, that permits use of this software under different terms (including support and maintenance services).

Please contact a12-license@mgm-tp.com for more information.
    
You must select and comply with exactly one of the above license options.

Warranty Disclaimer (applies to either option)
THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTY OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT, EXCEPT WHERE SUCH DISCLAIMERS ARE HELD TO BE LEGALLY INVALID. SEE THE RESPECTIVE LICENSE TEXT FOR DETAILS. 
////
[#/overview-engine/localization]
= Localization

An application using Overview Engine has to provide a `LocalizerContext` instance from `util-localization-react` package.

The context can be initialized by using `DefaultLocalizerContextProvider`, or customized completely by passing
three parameters: `localizer`, `locale`, and `dataFormats` into `LocalizerContext`.

`localizer` receives an array of Localizables and returns resolved
string in regard to current `locale`. For more details, see link:/docs/UTILS_LOCALIZATION/utils-localization-documentation-bundle/index.html[Utils localization documentation].

== API

Overview Engine offers two alternative localization approaches:

* In which the React hooks are available, link:./assets/generated/typedoc/modules/services_localization_internal_localizer-hooks.LocalizerHooks.html[LocalizerHooks] namespace with four different hooks can be used:
** `useLocalizedResource`: to translate Overview Engine resources via public `RESOURCE_KEYS`.
** `useLocalizedOverviewElement`: to translate localized texts in Overview Model's elements.
** `useLocalizedFieldLabel`: to translate field labels in the Document Model.
** `useLocalizedFieldValue`: to translate values of localizable fields (BooleanType, ConfirmType, EnumerationType).
** `useLocalizedDateFieldFormat`: to translate the date format string of a date field in the Document Model.

* In which the React hooks are not available, link:./assets/generated/typedoc/modules/services_localization_internal_localizable-factory.LocalizableFactory.html[LocalizableFactory] namespace with alternative functions can be used to create
corresponding localizables.

== Resource Keys
Resource keys are used to identify the document elements and UI elements that are localized. There are two kinds of resource keys: static resource keys and model element keys.

=== Static Resource Keys

Static resource keys are fixed and not changed. For example, the labels for `Confirm` and `Cancel` in confirmation dialog or input labels in filter option views are identified by static resource keys.

These keys are provided in the constant link:./assets/generated/typedoc/variables/services_localization_internal_languages_keys.RESOURCE_KEYS.html[`RESOURCE_KEYS`] map and exported from link:./assets/generated/typedoc/modules/services_localization.html[services/localization].

=== Model Element Keys

Model element keys are dynamically generated based on the model being used.
The following table summarizes the key formats:

[%header,cols="1,3"]
|===
|Element                          |Key
|Table header label               a|`uiModel.{overview-model-name}.header.label`
|Column header label              a|`uiModel.{overview-model-name}.columns.{column-id}.label`
|Number column suffix             a|`uiModel.{overview-model-name}.columns.{column-id}.suffix`
|Sub-header action                a|`uiModel.{overview-model-name}.subHeaderBox.actions.{button-event}.(label\|title)`
|Sub-header action confirmation   a|`uiModel.{overview-model-name}.subHeaderBox.actions.{button-event}.confirmation.(title\|message)`
|Footer action                    a|`uiModel.{overview-model-name}.footerBox.actions.{button-event}.(label\|title)`
|Footer action confirmation       a|`uiModel.{overview-model-name}.footerBox.actions.{button-event}.confirmation.(title\|message)`
|Row action                       a|`uiModel.{overview-model-name}.rowActionGroup.actions.{action-event}.(label\|title)`
|Context menu action              a|`uiModel.{overview-model-name}.contextMenu.actions.{action-event}.(label\|title)`
|Multi-selection action              a|`uiModel.{overview-model-name}.multiSelection.actions.{action-event}.(label\|title)`
|Multi-selection action confirmation a|`uiModel.{overview-model-name}.multiSelection.actions.{button-event}.confirmation.(title\|message)`
|Multi-selection clear confirmation  a|`uiModel.{overview-model-name}.multiSelection.clearConfirmation.(title\|message)`
|Row action confirmation          a|`uiModel.{overview-model-name}.rowActionGroup.actions.{action-event}.confirmation.(title\|message)`
|Context action confirmation      a|`uiModel.{overview-model-name}.contextMenu.actions.{action-event}.confirmation.(title\|message)`
|Action group title               a|`uiModel.{overview-model-name}.contextMenu.groups.{group-name}`
|Filter selector Other section label a|`uiModel.{overview-model-name}.filterSelector.section.other`
|===

== Customization

The following snippet demonstrates the way to modify a label of row action confirmation dialog in American English.

[source,typescript,title="Localization Customization"]
----
include::./assets/typescript/features/custom-localization.tsx[tags="customLocalization"]
----
