////
SPDX-License-Identifier: EUPL-1.2 OR LicenseRef-commercial
Copyright (c) 2012-2026 mgm technology partners GmbH
Dual License
This source file is part of the mgm A12 Platform and available under a choice of two different licenses:
1. Open-Source License - EUPL v1.2
You may redistribute and/or modify this file under the terms of the European Union Public License, version 1.2 - see https://eupl.eu/.
2. Commercial License
Alternatively, you may obtain a commercial license from mgm technology partners GmbH, that permits use of this software under different terms (including support and maintenance services).

Please contact a12-license@mgm-tp.com for more information.

You must select and comply with exactly one of the above license options.

Warranty Disclaimer (applies to either option)
THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTY OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT, EXCEPT WHERE SUCH DISCLAIMERS ARE HELD TO BE LEGALLY INVALID. SEE THE RESPECTIVE LICENSE TEXT FOR DETAILS. 
////
= Conversion

The Overview Engine utilizes the Conversion API from the utils-localization package to handle value conversions
between document data and rendered UI values, considering the current locale and data formats.

The utils-localization `ValueConversion` interface has two methods:

    - `parseValue`: converts the rendered UI value to the document value.
    - `formatValue`: converts the document value to the rendered UI value.

When rendering a document value, the Overview Engine calls the `formatValue` method of the contextual `conversion`,
which implements the `ValueConversion` interface and is extracted from `LocalizerContext`.
This method is provided with the value to be converted, along with relevant information such as
the document model name and the model path to the field or group.
Depending on the element type, additional information may be passed,
such as `minFractionalDigits` for `NumberType` elements and `format` for `DateType` elements.

Similarly, when parsing a value, the `parseValue` method is called with the similar parameters.

For more details, please refer to the utils-localization documentation.

To customize the conversion logic, you can provide a custom implementation of the Conversion API.
For example, to customize the format of a `DateType` field named `DateOfBirth` in the `PersonDM` document model:

[source,typescript,title="Conversion customization"]
----
include::./assets/typescript/features/conversion.tsx[tags="main"]
----
