////
SPDX-License-Identifier: EUPL-1.2 OR LicenseRef-commercial
Copyright (c) 2012-2026 mgm technology partners GmbH
Dual License
This source file is part of the mgm A12 Platform and available under a choice of two different licenses:
1. Open-Source License - EUPL v1.2
You may redistribute and/or modify this file under the terms of the European Union Public License, version 1.2 - see https://eupl.eu/.
2. Commercial License
Alternatively, you may obtain a commercial license from mgm technology partners GmbH, that permits use of this software under different terms (including support and maintenance services).

Please contact a12-license@mgm-tp.com for more information.
    
You must select and comply with exactly one of the above license options.

Warranty Disclaimer (applies to either option)
THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTY OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT, EXCEPT WHERE SUCH DISCLAIMERS ARE HELD TO BE LEGALLY INVALID. SEE THE RESPECTIVE LICENSE TEXT FOR DETAILS. 
////
= Custom Time Format

Since version 36.1.0, there are two ways to change the time format (12h or 24h format) in the date time and time picker:

1. Use the `timeMode` (12h or 24h) property in `OverviewEngine` component.
2. Customize the `DateTimeFilterOptionsView` and/or `TimeFilterOptionsView`  component from `FilterOptionsViews` in `componentMap` and provide the `timeMode` (12h or 24h) prop.

NOTE: The local props always have higher priority, thus `DateTimeFilterOptionsView` or `TimeFilterOptionsView`'s `timeMode` can be able to override the global one from the `OverviewEngine`.

NOTE: By default, the 12-hour format will be used.

The following examples demonstrate how to customize the time mode using two different ways to show the 24h format:

[source,typescript,options="nowrap",title="Provide time mode in OverviewEngine component"]
----
include::./assets/typescript/features/time-format-overview-engine.tsx[tags="time-mode-in-overview-engine-component"]
----

[source,typescript,options="nowrap",title="Customize the DateTimeFilterOptionsView"]
----
include::./assets/typescript/features/time-format-date-time-filter-options-view.tsx[tags="custom-date-time-filter-options-view"]
----

