////
SPDX-License-Identifier: EUPL-1.2 OR LicenseRef-commercial
Copyright (c) 2012-2026 mgm technology partners GmbH
Dual License
This source file is part of the mgm A12 Platform and available under a choice of two different licenses:
1. Open-Source License - EUPL v1.2
You may redistribute and/or modify this file under the terms of the European Union Public License, version 1.2 - see https://eupl.eu/.
2. Commercial License
Alternatively, you may obtain a commercial license from mgm technology partners GmbH, that permits use of this software under different terms (including support and maintenance services).

Please contact a12-license@mgm-tp.com for more information.

You must select and comply with exactly one of the above license options.

Warranty Disclaimer (applies to either option)
THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTY OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT, EXCEPT WHERE SUCH DISCLAIMERS ARE HELD TO BE LEGALLY INVALID. SEE THE RESPECTIVE LICENSE TEXT FOR DETAILS.
////
= Custom Time Format

Starting with version 39.0.0, the time format (12h or 24h) is configured globally via the `DateTimeContext` from `@com.mgmtp.a12.widgets/widgets-core`. The previous `timeMode` prop on `OverviewEngine` and on the `DateTimeFilterOptionsView` / `TimeFilterOptionsView` components has been removed.

Wrap the application (or a subtree containing the `OverviewEngine`) in a `DateTimeContext.Provider` and set `timeMode` to `"12h"` or `"24h"`. All datetime widgets rendered below the provider pick up the value automatically.

NOTE: When no `DateTimeContext.Provider` is set, widgets fall back to the 12-hour format.

The following example demonstrates how to configure the 24-hour format globally for the Overview Engine:

[source,typescript,options="nowrap",title="Provide time mode via DateTimeContext"]
----
include::./assets/typescript/features/time-format-overview-engine.tsx[tags="time-mode-in-overview-engine-component"]
----
