//// 
SPDX-License-Identifier: EUPL-1.2 OR LicenseRef-commercial
Copyright (c) 2012-2026 mgm technology partners GmbH
Dual License
This source file is part of the mgm A12 Platform and available under a choice of two different licenses:
1. Open-Source License - EUPL v1.2
You may redistribute and/or modify this file under the terms of the European Union Public License, version 1.2 - see https://eupl.eu/.
2. Commercial License
Alternatively, you may obtain a commercial license from mgm technology partners GmbH, that permits use of this software under different terms (including support and maintenance services).

Please contact a12-license@mgm-tp.com for more information.
    
You must select and comply with exactly one of the above license options.

Warranty Disclaimer (applies to either option)
THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTY OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT, EXCEPT WHERE SUCH DISCLAIMERS ARE HELD TO BE LEGALLY INVALID. SEE THE RESPECTIVE LICENSE TEXT FOR DETAILS. 
////
[#/selector-map]
= Custom SelectorMap

[NOTE]
====
This API is marked as experimental. Breaking changes *might* happen even in minor releases.
====

The `SelectorMap` can be used to customize certain state access of the Overview Engine.
The Overview Engine internally uses a default variant of this map, but you can provide your own implementation
containing your customizations as a prop for Overview Engine View Component.
Then it will be used in place of the default one.

For example, customizing the way the Overview Engine selects attachment thumbnails can look like this:

[source,typescript]
----
import {
	DefaultSelectorMap,
	type SelectorMap
} from "@com.mgmtp.a12.overviewengine/overviewengine-core/lib/main/view/configuration/selector-map.js";

/**
 * The default selector looks up thumbnails by id
 *
 * Here, we use the content property of attachments instead.
 * If it does not exist, we fall back to the default selector.
 */
const CustomSelectorMap: SelectorMap = {
	...DefaultSelectorMap,
	attachmentThumbnail: (attachment) => {
		return (state) =>
			attachment.content?.startsWith("data:image/")
				? attachment.content
				: DefaultSelectorMap.attachmentThumbnail(attachment)(state);
	}
}
----

Note that it is mandatory to spread the `DefaultSelectorMap` when customizing (similar to `WidgetMap` and `ComponentMap`).
